#!/bin/bash
# Source the environment script containing the install function 
 # source environment 
  
 # Constants ######## 
 readonly WAITLONG=3 
 readonly WAITSMALL=1 
 #################### 
  
 install() 
 { 
         sleep $WAITLONG 
         pkg install -y $1 
 }

# Install applications

# Main function
main(){
    # Install Applications


	# echo ">>> Installing Python 3 ..."
	echo "# Python is a robust programming and scripting language"
	    install python3.8.10


}

# The main app
main
