#!/bin/bash
source env

# Install applications

# Main function
main(){
    # Install Applications


	# echo ">>> Installing Python 3 ..."
	echo "# Python is a robust programming and scripting language"
	    install python3.8.10


}

# The main app
main
