#!/bin/bash

# Install AWS CLI version 2

# Main function
main() {
    install_aws_cli_v2
}

# Download and Install AWS CLI version 2
install_aws_cli_v2() {
    # Download the AWS CLI version 2 installation script
    curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"

    # Unzip the installation script
    unzip awscliv2.zip

    # Run the installation script with a custom installation directory in your home directory
    ./aws/install -i ~/ -b ~/bin

    # Clean up
    rm -rf aws awscliv2.zip

    # Check if the installation was successful
    if [ $? -eq 0 ]; then
        echo "AWS CLI version 2 has been successfully installed."
        echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc  # Add the binary directory to your PATH
        source ~/.bashrc  # Apply the changes to your current shell session
        aws --version
    else
        echo "Failed to install AWS CLI version 2."
        exit 1
    fi
}

# Run the main function
main
