#!/bin/bash

# Author: Samuel Anyaele
# Source: TheMobileProf.com

echo "TheMobileProf.com recommended Setup for Termux.
Press Y/y to continue:"
read INSTALL
# Only continue if user says Yes
if [ ${INSTALL,,} != 'y' ]; then
   exit 0
fi


echo "Updating Termux ..."
sleep 2
# Answer "Y" to all prompts
yes Y | pkg update

sleep 1
echo "
Installing Unzip...
# Unzip is an archiving and extraction package"
sleep 3
pkg install -y unzip


# PACKAGE INSTALLATIONS #
sleep 1
echo "
Installing openssl and openssh ...
# Enable secure remote connection from a terminal"
sleep 3
pkg install -y openssl openssh
cat /dev/zero | ssh-keygen -q -N ""


sleep 1
echo "
Installing Git and Gh...
# Git is a Version Control system for storing and distributing software, and Gh is the official Github CLI"
sleep 3
pkg install -y git
pkg install -y gh



sleep 1
echo "
Now let's configure Git ..."
sleep 1
echo "What is your name?"
read USERNAME
git config --global user.name "$USERNAME"

echo "What is your email? (preferably github.com email)"
read USEREMAIL
git config --global user.email $USEREMAIL

# Merge setup
git config --global pull.rebase false



sleep 1
echo "
Installing Neovim ...
# Neovim is a robust terminal code editor that is forked from Vim"
sleep 3
pkg install -y neovim




sleep 1
echo "
Installing Python 3 ...
# Python is a robust programming and scripting language"
sleep 3
pkg install -y python





sleep 1
echo "\n \n Installing Nodejs & npm ...
# NodeJs enables server-side Javascript"
sleep 3
pkg install -y nodejs





sleep 1
echo "
Setup Neovim ..."
sleep 3
# Install vim-plug
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Ensure ~/.config/nvim has been created
NVIMDIR=~/.config/nvim
if [[ ! -d "$NVIMDIR" ]] 
then
	mkdir -p $NVIMDIR
fi

# Ensure ~/env/init.vim exists
NVIMFILE=~/env/init.vim
if [[ ! -f "$NVIMFILE" ]] 
then
	git clone https://github.com/themobileprof/env ~/env
fi

# Copy the Neovim config file ~/env/init.vim to ~/.config/nvim
cp $NVIMFILE $NVIMDIR



# Run :PlugInstall on Neovim
echo "
Installing Neovim plugins ..."
sleep 2
nvim --headless +PlugInstall +qall


# Configure COC
enable_lang (){ 
	if [ "${3,,}" = "y" ]; then
        	$REPLY = "Y"
	else
		echo "Enable $1 support for Neovim? Y/n"
		read REPLY
	fi

	if [ "${REPLY,,}" = "y" ]; then
		nvim +"CocInstall -sync coc-$2" +qall
		echo "Enabled $1
		+++++++"
		sleep 1
	else
		echo "$1 not enabled
		-------"
	fi
}


# Install Prettier
echo "
Installing prettier ..."
nvim +'CocInstall -sync coc-prettier' +qall

# Ascertain if user would like to autoinstall Neovim plugins
echo "Would you like to auto install language support in Neovim? Y/n"
read ALLYES

# Language support for CSS
enable_lang CSS css ALLYES

# Language support for HTML
enable_lang HTML html ALLYES

# Language support for Javascript
enable_lang Javascript tsserver ALLYES

# Language support for Python
enable_lang Python pyright ALLYES

# Language support for PHP
enable_lang PHP phpls ALLYES

# Language support for YAML
enable_lang YAML yaml ALLYES

# Language support for GIT
enable_lang GIT git ALLYES

# Language support for SQL
enable_lang SQL sql ALLYES

# Language support for Json
enable_lang JSON json ALLYES

# Language support for Bash
enable_lang Bash sh ALLYES

# Finalize config
echo "
Finalizing Neovim configuration"
sleep 3
nvim +CocUpdateSync +qall



sleep 1
echo "
Changing Welcome Page"
sleep 2
#backup existing file
cd ~
cp ../usr/etc/motd ../usr/etc/motd.bak
#make new welcome file
echo "xxxxxxxxxxxxxxxxx
Hi $USERNAME!

Welcome to Termux
xxxxxxxxxxxxxxxxx

TheMobileProf.com Scripts Repo:
https://github.com/themobileprof/scripts

Recommended Keyboard:
Hacker's Keyboard (https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)

For help, try:
~/help/start
" > ../usr/etc/motd
cd ~

termux-setup-storage


sleep 1
echo "
Install Zsh"
sleep 3
bash -c "$(curl -fsSL https://git.io/oh-my-termux)"

# Finalizing setup
sleep 2
