#!/bin/bash

# Author: Samuel Anyaele
# Source: TheMobileProf.com
#
# The installation Bash file for 
# TheMobileProf MobileOps project 
# https://github/themobileprof/mobileops
#
# MobileOps simplifies development on mobile for Beginners

# Installation function
installations(){
	sleep 3
	echo "Installing $1..."
	sleep 1
	pkg install -y $1
}


echo "TheMobileProf.com recommended Setup for Termux.
Press Y/y to continue:"
read INSTALL
# Only continue if user says Yes
if [ ${INSTALL,,} != 'y' ]; then
   exit 0
fi


########################
# UPDATE TERMUX PACKAGES
echo "Updating Termux ..."
sleep 2
# Answer "Y" to all prompts
yes Y | pkg update




########################
# INSTALL UNZIP
echo "# Unzip is an archiving and extraction package"
installations unzip




########################
# INSTALL OPENSSL & OPENSSH
echo "# Enable secure remote connection from a terminal"
installations openssh
installations openssl
cat /dev/zero | ssh-keygen -q -N ""




########################
# INSTALL VERSION CONTROL
echo "
# Git is a Version Control system for storing and distributing software, and Gh is the official Github CLI"
installations git
installations gh



sleep 1
echo "
Now let's configure Git ..."
sleep 1
echo "What is your name?"
read USERNAME
git config --global user.name "$USERNAME"

echo "What is your email? (preferably github.com email)"
read USEREMAIL
git config --global user.email $USEREMAIL

# Merge setup
git config --global pull.rebase false




########################
# INSTALL SCRIPTING LANGUAGES
# Python
echo "
	# Python is a robust programming and scripting language"
installations python

# PHP
echo "
	# PHP powers 80% of the Web"
installations php

# Javascript on Node
echo "
	# NodeJs enables server-side Javascript"
installations nodejs




########################
# DATABASE
# SQLite
echo "
	# SQLite is a lightweight SQL database"
installations sqlite




########################
# TERMINAL CODE EDITOR
# Neovim install
echo "
	# Neovim is a robust terminal code editor that is forked from Vim"
installations neovim

# Neovim Setup
sleep 1
echo "
Setup Neovim ..."
sleep 3
# Install vim-plug
curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Ensure ~/.config/nvim has been created
NVIMDIR=~/.config/nvim
if [[ ! -d "$NVIMDIR" ]] 
then
	mkdir -p $NVIMDIR
fi

# Ensure ~/env/init.vim exists
NVIMFILE=~/env/init.vim
if [[ ! -f "$NVIMFILE" ]] 
then
	git clone https://github.com/themobileprof/env ~/env
fi

# Copy the Neovim config file ~/env/init.vim to ~/.config/nvim
cp $NVIMFILE $NVIMDIR

# Run :PlugInstall on Neovim
echo "
Installing Neovim plugins ..."
sleep 2
nvim --headless +PlugInstall +qall

# Function: Configure COC
enable_lang (){
	echo "Enable $1 support for Neovim? Y/n"
	read REPLY
	if [ "${REPLY,,}" = "y" ]; then
		nvim +"CocInstall -sync coc-$2" +qall
		echo "Enabled $1
		+++++++"
		sleep 1
	else
		echo "$1 not enabled
		-------"
	fi
}

# Install Prettier
echo "
Installing prettier ..."
nvim +'CocInstall -sync coc-prettier' +qall


# Language support for CSS
enable_lang CSS css

# Language support for HTML
enable_lang HTML html

# Language support for Javascript
enable_lang Javascript tsserver

# Language support for Python
enable_lang Python pyright

# Language support for PHP
enable_lang PHP phpls

# Language support for YAML
enable_lang YAML yaml

# Language support for GIT
enable_lang GIT git

# Language support for SQL
enable_lang SQL sql

# Language support for Json
enable_lang JSON json

# Language support for Bash
enable_lang Bash sh

# Finalize config
echo "
Finalizing Neovim configuration"
sleep 3
nvim +CocUpdateSync +qall




########################
# CLONE MOBILEOPS REPO
sleep 1
echo "
Cloning TheMobileProf MobileOps tools"
sleep 2
cd ~
git clone https://github.com/themobileprof/mobileops mobileops
cd -




########################
# CHANGE WELCOME PAGE
sleep 1
echo "
Changing Welcome Page"
sleep 2
#backup existing file
cd ~
cp ../usr/etc/motd ../usr/etc/motd.bak
#make new welcome file
echo "Hi $USERNAME!

Welcome to Termux
xxxxxxxxxxxxxxxxx

TheMobileProf.com Scripts Repo:
https://github.com/themobileprof/scripts

Recommended Keyboard:
Hacker's Keyboard (https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)

For help, try:
~/mobileops/start

" > ../usr/etc/motd
cd -




########################
# INSTALL ZSH
sleep 1
echo "
Install Zsh"
sleep 3
bash -c "$(curl -fsSL https://git.io/oh-my-termux)"

# Finalizing setup
sleep 2
