#!/bin/bash

# Author: Samuel Anyaele
# Source: TheMobileProf.com

cd ~/help

echo "What do you want to work on?
1. Git/Github
2. Database (Not Available)
3. File Upload (Not Available)
4. Cloud Resources (Not Available)
0. To exit
"
read -p "Select a menu number (1-4): " MENU

PYTHON=`which python`

if [ "$MENU" = "1" ]; then
	$PYTHON git.py
fi
